
project_id = "emtebosiacxihwrfcylr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.hello-world]
verify_jwt = false

[functions.get-profile]
verify_jwt = true

[functions.update-profile]
verify_jwt = true

[functions.auth-role-validation]
verify_jwt = true

[functions.geo-verification]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.shift-matching]
verify_jwt = true

[functions.shift-status-update]
verify_jwt = true
