// src/data/demoShifts.ts
import { MarketUpdate } from '@/services/marketData.service';

// Demo data for the market updates
export const demoShifts: MarketUpdate[] = [
  {
    id: 'demo-1',
    type: 'URGENT',
    title: 'Senior Bartender Needed',
    location: 'Grand Hotel & Resort',
    region: 'North America',
    rate: '$35/hr',
    urgency_level: 'high',
    highlight: true,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 9000000 // 2.5 hours ago
  },
  {
    id: 'demo-12',
    type: 'SWAP',
    title: 'Banquet Server - Wedding',
    location: 'Garden Palace',
    region: 'Asia Pacific',
    rate: '$28/hr',
    urgency_level: 'medium',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 4500000 // 75 minutes ago
  },
  {
    id: 'demo-13',
    type: 'URGENT',
    title: 'Barista Needed ASAP',
    location: 'Airport Lounge',
    region: 'Middle East',
    rate: '$25/hr',
    urgency_level: 'high',
    highlight: true,
    isNew: true,
    isUpdating: false,
    timestamp: Date.now() - 1500000 // 25 minutes ago
  },
  {
    id: 'demo-14',
    type: 'REGULAR',
    title: 'Room Service Attendant',
    location: 'Boutique Hotel',
    region: 'Europe',
    rate: '€20/hr',
    urgency_level: 'low',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 18000000 // 5 hours ago
  },
  {
    id: 'demo-15',
    type: 'PREMIUM',
    title: 'Casino Dealer - Poker',
    location: 'Grand Casino',
    region: 'North America',
    rate: '$32/hr',
    urgency_level: 'medium',
    highlight: true,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 8100000 // 2.25 hours ago
  }
];.now() - 10800000 // 3 hours ago
  },
  {
    id: 'demo-8',
    type: 'SWAP',
    title: 'Front Desk Agent - Weekend',
    location: 'Business Hotel',
    region: 'Middle East',
    rate: '$26/hr',
    urgency_level: 'medium',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 5400000 // 1.5 hours ago
  },
  {
    id: 'demo-9',
    type: 'URGENT',
    title: 'Head Chef Substitute',
    location: 'Michelin Star Restaurant',
    region: 'Europe',
    rate: '€45/hr',
    urgency_level: 'high',
    highlight: true,
    isNew: true,
    isUpdating: false,
    timestamp: Date.now() - 600000 // 10 minutes ago
  },
  {
    id: 'demo-10',
    type: 'PREMIUM',
    title: 'Sommelier for Wine Tasting',
    location: 'Luxury Vineyard Resort',
    region: 'Europe',
    rate: '€38/hr',
    urgency_level: 'medium',
    highlight: true,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 2700000 // 45 minutes ago
  },
  {
    id: 'demo-11',
    type: 'REGULAR',
    title: 'Restaurant Server',
    location: 'Seafood Grill',
    region: 'North America',
    rate: '$24/hr',
    urgency_level: 'low',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 1200000 // 20 minutes ago
  },
  {
    id: 'demo-2',
    type: 'PREMIUM',
    title: 'Event Host - Corporate Gala',
    location: 'City Convention Center',
    region: 'North America',
    rate: '$30/hr',
    urgency_level: 'medium',
    highlight: true,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 3600000 // 1 hour ago
  },
  {
    id: 'demo-3',
    type: 'SWAP',
    title: 'Wait Staff - Friday Night Shift',
    location: 'Oceanview Restaurant',
    region: 'North America',
    rate: '$25/hr',
    urgency_level: 'medium',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 7200000 // 2 hours ago
  },
  {
    id: 'demo-4',
    type: 'REGULAR',
    title: 'Kitchen Assistant',
    location: 'Downtown Bistro',
    region: 'Europe',
    rate: '€22/hr',
    urgency_level: 'low',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date.now() - 14400000 // 4 hours ago
  },
  {
    id: 'demo-5',
    type: 'URGENT',
    title: 'Concierge Needed Immediately',
    location: 'Luxury Plaza Hotel',
    region: 'Europe',
    rate: '£28/hr',
    urgency_level: 'high',
    highlight: true,
    isNew: true,
    isUpdating: false,
    timestamp: Date.now() - 900000 // 15 minutes ago
  },
  {
    id: 'demo-6',
    type: 'PREMIUM',
    title: 'VIP Server - Private Event',
    location: 'Celebrity Mansion',
    region: 'Asia Pacific',
    rate: '$40/hr',
    urgency_level: 'medium',
    highlight: true,
    isNew: true,
    isUpdating: false,
    timestamp: Date.now() - 1800000 // 30 minutes ago
  },
  {
    id: 'demo-7',
    type: 'REGULAR',
    title: 'Housekeeping Staff',
    location: 'Beach Resort',
    region: 'Asia Pacific',
    rate: '$22/hr',
    urgency_level: 'low',
    highlight: false,
    isNew: false,
    isUpdating: false,
    timestamp: Date